language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin
  - rm -rf target/debug/incremental/{async_nursery,build_script_build}-*
  - rm -rf target/debug/.fingerprint/async_nursery-*
  - rm -rf target/debug/build/async_nursery-*
  - rm -rf target/debug/deps/libasync_nursery-*
  - rm -rf target/debug/deps/async_nursery-*
  - rm -rf target/debug/{async_nursery,libasync_nursery}.d
  - cargo clean -p async_nursery


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      script:
        - bash ci/test.bash


    - name: linux nightly rust
      os  : linux
      dist: bionic # required for tarpaulin binary distribution to work.
      rust: nightly

      addons:
        apt:
          packages:
            - libssl-dev # for cargo-tarpaulin

      before_script:
        - cargo install --force cargo-audit
        - cargo generate-lockfile

      script:
        - bash ci/test.bash
        - bash ci/doc.bash
        - bash ci/coverage.bash
        - bash ci/deny.bash
        - cargo audit


    - name: osx stable rust
      os  : osx
      rust: stable

      script:
        - bash ci/test.bash


    - name: windows stable rust
      os  : windows
      rust: stable

      script:
        - bash ci/test.bash





